require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/line_items", type: :request do
  let(:product_) { create(:product) }
  let(:line_item) { create(:line_item, product: product_) }
  
  before do
    line_item
  end

  it 'updates line_item' do
    patch line_item_url(line_item), params: { line_item: { product_id: line_item.product_id } }

    expect(response).to redirect_to(line_item_url(line_item))
  end
end
