require 'rails_helper'
require 'support/database_cleaner'
require 'authentication_helpers'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  let(:user) { build(:user, password_confirmation: 'password') }

  context 'creates a new user with valid attributes' do
    it 'creates a new user' do
      expect do
        post users_url, params: { user: { name: user.name, password: user.password, password: user.password_confirmation } }, as: :json
      end.to change(User, :count).by(1)
    end

    it 'redirects to users url' do
      post users_url, params: { user: { name: user.name, password: user.password, password: user.password_confirmation } }, as: :html
      expect(response).to redirect_to(users_url)
    end
  end
end
